seb_undefined_shop_homepage:
    path:     /
    defaults: { _controller: SebUndefinedShopBundle:Shop:index }

seb_undefined_shop_order:
    path: /order
    defaults: { _controller: SebUndefinedShopBundle:Shop:order }

seb_undefined_shop_checkout:
    path: /checkout
    defaults: { _controller: SebUndefinedShopBundle:Shop:checkout }

seb_undefined_shop_final:
    path: /final
    defaults: { _controller: SebUndefinedShopBundle:Shop:final }
