services:
#    seb_undefined_shop.example:
#        class: SebUndefined\ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    seb_undefined_shop.services.check_date:
        class: SebUndefined\ShopBundle\Services\CheckDate
        arguments: ["@doctrine.orm.default_entity_manager"]
