<?php

namespace SebUndefined\ShopBundle\Repository;

/**
 * OrderMuseumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMuseumRepository extends \Doctrine\ORM\EntityRepository
{
}
