<?php

namespace SebUndefined\ShopBundle\Repository;


/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTicketForDay ($date, $number)
    {

        return $this->createQueryBuilder('t')
            ->select('COUNT(t) as nbTicket')
            ->from('SebUndefinedShopBundle:OrderMuseum', 'orderMuseum')
            ->innerJoin('orderMuseum.tickets', 'tickets')
            ->where('t.day = :day')
            ->andWhere('orderMuseum.complete = :complete')
            ->setParameters(array('day'=> $date->format('Y-m-d'), 'complete' => true) )
            ->getQuery()
            ->getSingleScalarResult();
    }
}
