<?php

namespace SebUndefined\ShopBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTicketForDay ($date, $number)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->where('t.day = :day')
            ->setParameter('day', $date->format('Y-m-d'))
            ->getQuery()
            ->getSingleScalarResult();
    }
}
